pull_request_rules:
    - name: Merge all pull requests
      conditions:
        - or:
            - files=package.json
            - files=package-lock.json
            - files=yarn.lock
      actions:
         merge:
           method: merge
