
on:
  push:
    branches: [ "new-page" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        pip install ImageScraper
        image-scraper https://techyleaf.com/
    - name: Commit and Push
      run: |
        git config user.name seyedeliasfakoorian
        git config user.email 98291494+seyedeliasfakoorian@users.noreply.github.com
        git add .
        git commit -m "Scrape Images"
        git push origin new-page
